apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: hirely
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: ghcr.io/zayedhamadi/user-service:latest
          ports:
            - containerPort: 8081

          envFrom:
            - configMapRef:
                name: user-service-config
            - secretRef:
                name: user-service-secret

          resources:
            requests:
              cpu: "150m"
              memory: "384Mi"
            limits:
              cpu: "600m"
              memory: "640Mi"

          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 30

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
            periodSeconds: 10
            failureThreshold: 6

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            periodSeconds: 15
            failureThreshold: 5
