apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-same-namespace-and-ingress
  namespace: hirely
spec:
  podSelector:
    matchExpressions:
      - key: app
        operator: NotIn
        values:
          - mysql
          - mongodb
          - keycloak
          - config-service
          - discovery-service
          - gateway
          - user-service
          - recrutement-service
          - frontend-service
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector: {}
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
