all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
  children:
    master:
      hosts:
        vmonee:
          ansible_host: 192.168.100.14
          ansible_connection: local
    workers:
      hosts:
        vmtwo:
          ansible_host: 192.168.100.10
          ansible_user: vmtwo
