apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: hirely
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      nodeSelector:
        kubernetes.io/hostname: vmtwo
      containers:
        - name: gateway
          image: ghcr.io/zayedhamadi/gateway:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

          envFrom:
            - configMapRef:
                name: gateway-config
            - secretRef:
                name: gateway-secret

          resources:
            requests:
              cpu: "200m"
              memory: "384Mi"
            limits:
              cpu: "750m"
              memory: "768Mi"

          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 30

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            periodSeconds: 10
            failureThreshold: 6

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            periodSeconds: 15
            failureThreshold: 5
