apiVersion: v1
kind: Service

metadata:
  name: config-service
  namespace: hirely
  labels:
    app: config-service
    component: backend

spec:
  type: ClusterIP

  selector:
    app: config-service

  ports:
    - name: http
      port: 8888
      targetPort: http
      protocol: TCP
