apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-service
  namespace: hirely
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: discovery-service
  template:
    metadata:
      labels:
        app: discovery-service
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: discovery-service
          image: ghcr.io/zayedhamadi/discovery-service:latest
          ports:
            - containerPort: 8761
          envFrom:
            - configMapRef:
                name: discovery-service-config

          resources:
            requests:
              cpu: "200m"
              memory: "384Mi"
            limits:
              cpu: "750m"
              memory: "768Mi"

          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 30

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            periodSeconds: 10
            failureThreshold: 6

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            periodSeconds: 15
            failureThreshold: 5
