apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service
  namespace: hirely
spec:
  replicas: 1
  revisionHistoryLimit: 3

  selector:
    matchLabels:
      app: frontend-service

  template:
    metadata:
      labels:
        app: frontend-service

    spec:
      nodeSelector:
        kubernetes.io/hostname: vmtwo
      imagePullSecrets:
        - name: ghcr-secret

      securityContext:
        runAsNonRoot: true
        fsGroup: 101

      containers:
        - name: frontend-service
          image: ghcr.io/zayedhamadi/frontend-microservice:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL

          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: nginx-cache
              mountPath: /var/cache/nginx
            - name: nginx-run
              mountPath: /var/run

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"

          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
      volumes:
        - name: tmp
          emptyDir: {}
        - name: nginx-cache
          emptyDir: {}
        - name: nginx-run
          emptyDir: {}

