apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-hirely-tls
  namespace: hirely
spec:
  secretName: api-hirely-tls-secret
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  dnsNames:
    - api.hirely.local
