apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app-hirely-tls
  namespace: hirely
spec:
  secretName: app-hirely-tls-secret
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  dnsNames:
    - app.hirely.local
