apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: hirely
spec:
  selector:
    app: keycloak
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: management
      port: 9000
      targetPort: 9000
