apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
data:
  policy.csv: |
    p, jenkins, applications, get, default/hirely, allow
    p, jenkins, applications, sync, default/hirely, allow
  policy.default: role:readonly
