apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hirely
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/zayedhamadi/hirely-devops
    targetRevision: main
    path: overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: hirely
  syncPolicy:
    automated:
      selfHeal: true
      prune: false
    syncOptions:
      - ApplyOutOfSyncOnly=true
